// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7_rK5e94sFEnjOW6jKyvewW-lj2xX7dE',
    appId: '1:480834795849:android:d8e352cbe9ad65bbe58298',
    messagingSenderId: '480834795849',
    projectId: 'authentication-app-1ffa2',
    storageBucket: 'authentication-app-1ffa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAExnTJoC7qpg7zTQswzY_BK6TQGliRIlg',
    appId: '1:480834795849:ios:7a287d2e530c58d1e58298',
    messagingSenderId: '480834795849',
    projectId: 'authentication-app-1ffa2',
    storageBucket: 'authentication-app-1ffa2.appspot.com',
    androidClientId: '480834795849-66nipj0p621s3u8c70q1tmg9rst5jau9.apps.googleusercontent.com',
    iosClientId: '480834795849-k5evd58g4c2ieuo1r664tarqeg7cjneg.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiEcommerce',
  );

}